git:
  depth: 5
language: node_js
cache:
  yarn: true
  directories:
    - "node_modules"
node_js:
  - "12.3.1"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn global add lerna jest
  - lerna bootstrap
matrix:
  include:
  - name: Core Pipeline
    env: PACKAGE_LOCATION=packages/core PACKAGE_NAME=@gradient-js/core
  - name: Css Pipeline
    env: PACKAGE_LOCATION=packages/css PACKAGE_NAME=@gradient-js/css
  - name: Svg Pipeline
    env: PACKAGE_LOCATION=packages/svg PACKAGE_NAME=@gradient-js/svg
script:
  - cd $PACKAGE_LOCATION
  - yarn test
  - yarn build
# before_deploy:
#   - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null
# deploy:
#   provider: script
#   script: "lerna publish"
#   skip_cleanup: true
#   on:
#     node: "8"
#     tags: true