git:
  depth: 5
language: node_js
cache:
  yarn: true
  directories:
    - "node_modules"
node_js:
  - "12.3.1"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"
script:
  - yarn install
  - yarn link
  - yarn build
  - yarn lint
  - yarn test
# before_deploy:
#   - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null
# deploy:
#   provider: script
#   script: "lerna publish"
#   skip_cleanup: true
#   on:
#     node: "8"
#     tags: true